// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCILZCDeVxnBixWMaxFUkXWSIn7Sc-kVnk',
    appId: '1:485008841512:web:2944b174b5226641c7ce1d',
    messagingSenderId: '485008841512',
    projectId: 'fishfinder-756b7',
    authDomain: 'fishfinder-756b7.firebaseapp.com',
    databaseURL: 'https://fishfinder-756b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishfinder-756b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlxXXEQsV293YTS_bEhIL1IvM0SXFOOSU',
    appId: '1:485008841512:android:1370381a732cd855c7ce1d',
    messagingSenderId: '485008841512',
    projectId: 'fishfinder-756b7',
    databaseURL: 'https://fishfinder-756b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishfinder-756b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2E5Fu3V2kN3HzFqV0JHTE3X1VOGJ_RVQ',
    appId: '1:485008841512:ios:71d7c1b5a306a0fbc7ce1d',
    messagingSenderId: '485008841512',
    projectId: 'fishfinder-756b7',
    databaseURL: 'https://fishfinder-756b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishfinder-756b7.appspot.com',
    iosBundleId: 'com.example.fishFinder',
  );

}